sudo: required
services:
  - docker

before_install:
  - docker build -t debajyotifse2/docker_react_frontend -f Dockerfile.dev .

script:
  - docker run debajyotifse2/docker_react_frontend npm run test -- --coverage
